-- Script historique limité aux brouillons.
-- Pour une nouvelle installation, exécuter plutôt supabase_setup.sql, qui crée
-- également les catalogues et le bucket nécessaire aux photos.
create table if not exists public.projects (
    id bigint generated by default as identity primary key,
    name text not null default 'Projet sans nom',
    form_data jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create index if not exists projects_updated_at_idx
    on public.projects (updated_at desc);
