-- Configuration complète de la persistance en ligne du générateur CCTP.
-- À exécuter une seule fois dans Supabase > SQL Editor.

create table if not exists public.modules (
    id bigint generated by default as identity primary key,
    marque text,
    reference text,
    nom_complet text,
    puissance_wc integer,
    type text,
    cadre text,
    backsheet text,
    dimensions text,
    longueur_cable text,
    poids text,
    garantie text,
    certif_carbone text,
    etn text,
    image text
);

create table if not exists public.onduleurs (
    id bigint generated by default as identity primary key,
    nom_complet text,
    marque text,
    reference text,
    puissance_kva double precision,
    type text,
    tension_nominale text,
    type_tension text,
    raccordement_dc text,
    para_dc text,
    para_ac text,
    afci text,
    garantie text,
    extension_garantie text,
    image text
);

create table if not exists public.integrations (
    id bigint generated by default as identity primary key,
    marque text,
    ref text,
    fixation text,
    compat1 text,
    compat2 text,
    compat3 text,
    compat4 text,
    compat5 text,
    carac1 text,
    carac2 text,
    carac3 text,
    carac4 text,
    carac5 text,
    image text,
    certification text,
    garantie text,
    notes text
);

create table if not exists public.integrations_caracteristiques (
    id bigint generated by default as identity primary key,
    integration_id bigint not null references public.integrations(id) on delete cascade,
    texte text not null
);

create table if not exists public.projects (
    id bigint generated by default as identity primary key,
    name text not null default 'Projet sans nom',
    form_data jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create index if not exists projects_updated_at_idx
    on public.projects (updated_at desc);
create index if not exists integrations_caracteristiques_integration_id_idx
    on public.integrations_caracteristiques (integration_id);

-- Le navigateur peut lire les images via leur URL publique. Les écritures et
-- suppressions restent effectuées uniquement par le serveur avec service_role.
insert into storage.buckets (id, name, public, file_size_limit)
values ('cctp-images', 'cctp-images', true, 10485760)
on conflict (id) do update
set public = excluded.public,
    file_size_limit = excluded.file_size_limit;

-- Aucun accès direct aux tables avec la clé publique Supabase. L'application
-- utilise exclusivement la clé service_role côté serveur, qui contourne RLS.
alter table public.modules enable row level security;
alter table public.onduleurs enable row level security;
alter table public.integrations enable row level security;
alter table public.integrations_caracteristiques enable row level security;
alter table public.projects enable row level security;

-- Demande à PostgREST de recharger immédiatement le nouveau schéma.
notify pgrst, 'reload schema';
